### ISSUE TITLE
Question about DateCreated

### ISSUE THREAD

**Issue by 2008zjqc** [HUD-Data-Lab/DataLab#1]
To whom it may concern,
We download the test kits from Sakai, and noticed that the DateCreated column is missing in both Enrollment and Exit CSVs. You may check DataLab - ES-NbN ESG.zip. Could anyone take a look and advice? Thanks very much. 

Best,
Chen

**Comment by HUD-Data-Lab** [comment]
Thank you for flagging this! Fix is currently underway, we'll alert you here when you can re-download.

**Comment by HUD-Data-Lab** [comment]
The files with missing columns have been replaced. Please do not hesitate to let us know if you have any further concerns!
