### ISSUE TITLE
9b formatting checks

### ISSUE THREAD

**Issue by jessedirkman-ica** [HUD-Data-Lab/DataLab#10]
- "Total" label in A3 should read "Percent of Assessed Prioritized Of the total HH Assessed report the percent of those placed on the prioritization list"
- Confirm data types.  While not specified in specs, I'd expect integers in B1:F2.  Also not sure how NaNs should be displayed, maybe as empty cell?

**Comment by jessedirkman-ica** [comment]
[Note: 9b changes NaN to zero]

**Comment by HUD-Data-Lab** [comment]
Data in the decimal columns looks like integers for whole number cells when exported to a csv, this is tentatively fine for now. NaNs are transformed into either a 0 or an empty string when exported, depending on the data type for that column.

**Comment by HUD-Data-Lab** [comment]
Fixed by c25f0e51dfcedab31dc08901be422edc4bbf644c
