### ISSUE TITLE
9d Formatting Checks

### ISSUE THREAD

**Issue by jessedirkman-ica** [HUD-Data-Lab/DataLab#12]
- Labels in A1-A14, A17-A19 do not match specs.  (I do like the scripted labels for A1-A14 better, though, if changing the specs instead is an option.)
- Confirm data types. While not specified in specs, I'd expect integers in all rows except for 16 and 22. Also not sure how NaNs should be displayed, maybe as empty cell?

**Comment by HUD-Data-Lab** [comment]
Data in the decimal columns looks like integers for whole number cells when exported to a csv, this is tentatively fine for now. NaNs are transformed into either a 0 or an empty string when exported, depending on the data type for that column,

**Comment by HUD-Data-Lab** [comment]
Fixed by c25f0e51dfcedab31dc08901be422edc4bbf644c
