### ISSUE TITLE
Warning while running file CE_APR.R

### ISSUE THREAD

**Issue by rokeya2023** [HUD-Data-Lab/DataLab#13]
After executing line 95 in RStudio the following warning message displayed in the console:
![image](https://user-images.githubusercontent.com/120743917/208927277-4e410c23-2ea5-469e-9144-5a66d84cf56a.png)

**Comment by HUD-Data-Lab** [comment]
Some warnings are to be expected; you'll see those when dates of birth are missing. That seems high, though--can you run `warnings()` and post a screenshot of the results?

**Comment by rokeya2023** [comment]
I added the Screenshots for the RScript and the R Console:
After executing line #95 in R studio, the following 26 warnings displayed in the console. The screenshot for the RScript and R Console provided. (File CE_APR.R)
Screenshot for RScript:
![image](https://user-images.githubusercontent.com/120743917/209143949-e92aa09a-7966-4497-b3b6-4af983722fd9.png)

Screenshot for the R Console:
![image](https://user-images.githubusercontent.com/120743917/209144056-8226ebe7-6da3-470f-ba55-d3c3f1fa5d9e.png)
![image](https://user-images.githubusercontent.com/120743917/209144155-2e54f678-0a01-4706-97cf-b437fa195b9b.png)
![image](https://user-images.githubusercontent.com/120743917/209144220-83b2a9de-fdb2-4391-a61f-bb424a721b46.png)
![image](https://user-images.githubusercontent.com/120743917/209144266-3ddb8081-7fdd-4be0-8209-2710c2487e57.png)
![image](https://user-images.githubusercontent.com/120743917/209144309-73c90caf-a3cc-4420-a9a9-7433e3b80368.png)
![image](https://user-images.githubusercontent.com/120743917/209144394-3ab362a1-9535-4a6c-adeb-9dcc9f900db3.png)
![image](https://user-images.githubusercontent.com/120743917/209144441-e0b762c2-a264-4d34-b205-323c62d7254f.png)
![image](https://user-images.githubusercontent.com/120743917/209144480-4efb945c-4d8a-437e-8681-fbb271e91675.png)
![image](https://user-images.githubusercontent.com/120743917/209144526-56ffe88b-3775-4f61-805c-1f25d5a31d21.png)

**Comment by HUD-Data-Lab** [comment]
Thanks for sharing all these! This is okay--it throws these warnings when we have clients with missing DOBs, which is unfortunate but also the reality of data entry in most CoCs.
