### ISSUE TITLE
Error occurred while uploading the source("Datalab.R")

### ISSUE THREAD

**Issue by rokeya2023** [HUD-Data-Lab/DataLab#14]
While uploading the source file:
source("DataLab.R") There was an error message generated regarding rename() function.
![image](https://user-images.githubusercontent.com/120743917/209145038-a4bf9549-7b72-48aa-90b0-9ae3f3761992.png)
The following error displayed in the console
![image](https://user-images.githubusercontent.com/120743917/209147245-96fe2c3a-9963-47d8-a63f-9e9f15ab5c94.png)
![image](https://user-images.githubusercontent.com/120743917/209147273-4a4d7b00-465c-4497-94be-c92a7308bd63.png)
![image](https://user-images.githubusercontent.com/120743917/209147352-21a70000-0f0a-48f8-8906-0b8a55813166.png)

**Comment by HUD-Data-Lab** [comment]
Ooh, important step--if you're re-running the DataLab.R file, you'll want to clear your environment first. That will prevent this error!

**Comment by rokeya2023** [comment]
Thanks for the tip. Yah that's why I didn't get these before. I always have been cleaning the environment, just missed this time. Thanks again!!
