### ISSUE TITLE
datalab_functions.R -- [get_household_info] question

### ISSUE THREAD

**Issue by ZachEhmannICA** [HUD-Data-Lab/DataLab#15]
This may not be an issue, but just noticed that ProjectType for the HoH_HMID column of the temporary df "data" in this function only looks at project types 3 & 13. Should it also include 9 & 10?

This is line 1216 of datalab_functions.R

![image](https://user-images.githubusercontent.com/102747289/209168954-d32365e8-6ebc-4bf6-8d02-88edb57df673.png)

**Comment by HUD-Data-Lab** [comment]
Per page 17 of the [APR & CAPER specs](https://files.hudexchange.info/resources/documents/FY23-HMIS-Programming-Specifications-CoC-APR-and-ESG-CAPER.pdf), the move-in date is "only used when reporting on project types 3 and 13." Flagging this for future consideration if/when we use this code for other things, but for our current purposes this is fine.

**Comment by ZachEhmannICA** [comment]
Awesome, thank you for clarifying!
