### ISSUE TITLE
enrollment_CoC_over_time

### ISSUE THREAD

**Issue by jessedirkman-ica** [HUD-Data-Lab/DataLab#2]
Possible bug in enrollment_CoC_over_time, line 59 of CE_APR.R, or at least its use in 9a.

enrollment_CoC_over_time appears to filter enrollments to only those where CoCCode in EnrollmentCoC matches relevant_CoC & has InformationDate within enrollment.

Per pg 5 of the CE specs, however, it seems like element 3.16 (client location) should only come into play iff a project has multiple CoC codes.

Additionally, from #5 on pg 5, could 3.16 Information date be prior to entry, if it also meets the criteria of being <= [date of assessment] (4.19.1)?

**Comment by HUD-Data-Lab** [comment]
Bug flagged here is fixed by commit ab0c161d5a7688f8bc6169e7698b0d9cabd146de

**Comment by HUD-Data-Lab** [comment]
Right now we're linking 3.16 to the assessment/event by `EnrollmentID`, and there shouldn't be any information dates on the EnrollmentCoC.csv that are prior to the entry date. Flagging for discussion just in case.
