### ISSUE TITLE
clients_at_recent_assessment scope

### ISSUE THREAD

**Issue by jessedirkman-ica** [HUD-Data-Lab/DataLab#4]
Possible bug in clients_at_recent_assessment field, line 186 of CE_APR.R, related to use in 9a.  (More likely an issue of specification ambiguity re: which projects should be included in reporting than actual bug.)

This field includes all clients/rows from field client_plus, defined in line 95:
client_plus <- add_client_info(Enrollment)

Though it does not impact the results with our current test dataset, it looks like add_client_info pulls date_for_age from all enrollments, regardless of whether or not those enrollments are associated with CE.  

Consider a scenario where a 17 yr old is assessed for CE at the beginning of the reporting period, then enters shelter after turning 18 later in the year.  I think clients_at_recent_assessment would categorize this household as a "Without Children" household, when it should perhaps be a "With Only Children" household?

**Comment by HUD-Data-Lab** [comment]
The fix to #5 solves this issue as well, so resolved with ab0c161d5a7688f8bc6169e7698b0d9cabd146de
